backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Main Text", name: "main_text", widget: "markdown" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }

  - name: "about"
    label: "About Page"
    files:
      - file: "about.html"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "About Text", name: "about_text", widget: "markdown" }
          - { label: "Profile Image", name: "profile_image", widget: "image" }

  - name: "services"
    label: "Services Page"
    files:
      - file: "services.html"
        label: "Services"
        name: "services"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Service Description", name: "service_desc", widget: "markdown" }
          - { label: "Service Image", name: "service_image", widget: "image" }

  - name: "contact"
    label: "Contact Page"
    files:
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Contact Title", name: "contact_title", widget: "string" }
          - { label: "Contact Details", name: "contact_details", widget: "markdown" }
